# Config adapted from:
# https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows
env:
  global:
    - COVERALLS_PARALLEL=true
sudo: true
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - 12.14
    - os: linux
      services: docker
      language: node_js
      node_js:
        - 12.14
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libudev-dev
            - libusb-1.0-0-dev
            - g++-4.8
            - g++-4.8-multilib
            - icnsutils
            - graphicsmagick
            - xz-utils
            - xorriso
            - rpm

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install

script:
  - node --version
  - npm run package

after_success:
  - npm run coverage