language : node_js

env:
    jobs:
        - PROJECT_DIR=conseiljs-core
        - PROJECT_DIR=conseiljs-softsigner

node_js:
    - 12.16

cache:
    directories:
        - node_modules

before_script:
    - cd $PROJECT_DIR
    - npm install

script:
    - npm run package

after_success:
    - npm run coverage
