language : node_js

env:
    PROJECT_DIR=conseiljs
    PROJECT_DIR=conseiljs-softsigner

node_js:
    - 12.16
cache:
    directories:
        - node_modules

before_script:
    - npm install

script:
    - cd $PROJECT_DIR
    - npm run package

after_success:
    - npm run coverage
